const Data=[
    {id:0, 
     title:"Pizza",
     cal: 56,
    },
    {   id:1, 
        title:"Burger",
        cal: 69,
       },
       {id:2, 
        title:"Coke",
        cal: 500,
       },
       {id:3, 
        title:"Browne",
        cal: 180,
       },
       {id:4, 
        title:"Fried Rice",
        cal: 90,
       },
       {id:5, 
        title:"Lassania",
        cal: 200,
       },
       {id:6, 
        title:"Pani Puri",
        cal: 10,
       }
]

export default Data;